package io.tranto.core.jdbc;

import org.h2.jdbcx.JdbcDataSource;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Owns the JDBC {@link DataSource} and creates the schema the repositories and queue rely on. This
 * is the seam that makes the platform's persistence swappable: the standalone runtime uses an
 * in-memory H2 database here; a production deployment points the same code at Postgres or MySQL.
 *
 * <p>The schema is intentionally JSON-blob-plus-generated-columns: the full domain object lives in a
 * {@code value} CLOB (round-tripped by Jackson) while a few promoted columns ({@code namespace},
 * {@code state}, ...) make the common queries indexable — the exact shape Kestra's jOOQ layer uses.</p>
 */
public class JdbcDatabase {

    private final DataSource dataSource;

    public JdbcDatabase(final DataSource dataSource) {
        this.dataSource = dataSource;
    }

    /** @return an H2 database (in-memory, kept alive for the JVM) with the schema created. */
    public static JdbcDatabase h2InMemory(final String name) {
        return h2("jdbc:h2:mem:" + name + ";DB_CLOSE_DELAY=-1;MODE=PostgreSQL");
    }

    /**
     * @param url a full H2 JDBC URL (e.g. {@code jdbc:h2:file:./tranto-db;AUTO_SERVER=TRUE} to let
     *            several nodes share one on-disk database)
     * @return an H2 database with the schema created
     */
    public static JdbcDatabase h2(final String url) {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL(url);
        ds.setUser("sa");
        ds.setPassword("");
        JdbcDatabase db = new JdbcDatabase(ds);
        db.initSchema();
        return db;
    }

    /** @return a fresh connection from the pool (caller closes it). */
    public Connection connection() throws SQLException {
        return dataSource.getConnection();
    }

    /** Create the tables if they don't exist. Idempotent. ({@code data} avoids the reserved word {@code value}.) */
    public void initSchema() {
        String[] statements = {
            """
            CREATE TABLE IF NOT EXISTS flows (
                tenant     VARCHAR(200) NOT NULL DEFAULT '',
                namespace  VARCHAR(400) NOT NULL,
                id         VARCHAR(400) NOT NULL,
                revision   INT          NOT NULL DEFAULT 1,
                data       CLOB         NOT NULL,
                PRIMARY KEY (tenant, namespace, id)
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS executions (
                id         VARCHAR(64)  PRIMARY KEY,
                namespace  VARCHAR(400),
                flow_id    VARCHAR(400),
                state      VARCHAR(40),
                data       CLOB         NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS queue_messages (
                offset_id  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                topic      VARCHAR(100) NOT NULL,
                consumed   BOOLEAN      NOT NULL DEFAULT FALSE,
                claimed_at TIMESTAMP,
                claimed_by VARCHAR(64),
                data       CLOB         NOT NULL
            )
            """,
            // Idempotent columns for pre-existing (file-backed) databases created before the lease model.
            "ALTER TABLE queue_messages ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMP",
            "ALTER TABLE queue_messages ADD COLUMN IF NOT EXISTS claimed_by VARCHAR(64)",
            "CREATE INDEX IF NOT EXISTS idx_queue_poll ON queue_messages (topic, consumed, offset_id)",
            // Cluster-wide lease/lock rows (per-execution serialisation, scheduler leader election).
            """
            CREATE TABLE IF NOT EXISTS locks (
                name       VARCHAR(300) PRIMARY KEY,
                holder     VARCHAR(64)  NOT NULL,
                expires_at TIMESTAMP    NOT NULL
            )
            """,
            // Cluster-wide namespace key/value store (shared across nodes).
            """
            CREATE TABLE IF NOT EXISTS kv_store (
                namespace  VARCHAR(400) NOT NULL,
                kv_key     VARCHAR(400) NOT NULL,
                data       CLOB         NOT NULL,
                expires_at TIMESTAMP,
                PRIMARY KEY (namespace, kv_key)
            )
            """,
            // Cluster-wide per-flow concurrency slots: RUNNING rows count against the limit, QUEUED rows wait (FIFO by seq).
            """
            CREATE TABLE IF NOT EXISTS concurrency_slots (
                seq          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                flow_key     VARCHAR(900) NOT NULL,
                execution_id VARCHAR(64)  NOT NULL,
                status       VARCHAR(20)  NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_slots_flow ON concurrency_slots (flow_key, status, seq)",
            "CREATE INDEX IF NOT EXISTS idx_slots_exec ON concurrency_slots (execution_id)",
            // Cluster-wide object storage (shared blobs, addressed by tranto:///key).
            """
            CREATE TABLE IF NOT EXISTS storage_objects (
                obj_key    VARCHAR(900) PRIMARY KEY,
                data       VARBINARY    NOT NULL
            )
            """
        };
        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            for (String ddl : statements) {
                statement.execute(ddl);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("Failed to initialise JDBC schema", e);
        }
    }
}
